name: Daily Genesi Update
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install feedparser deep-translator
      - run: python genesi.py
      - run: |
          git config --global user.name "GenesiBot"
          git config --global user.email "bot@vrabo.it"
          git add -A
          git commit -m "🔄 Auto-update $(date +'%Y-%m-%d')" || echo "No changes"
          git push
